#!/usr/bin/env node
// Injects the PWA splash screen into all HTML files generated by expo export.
// Expo static export ignores web/index.html body content, so we post-process.

const fs = require('fs');
const path = require('path');

const DIST_DIR = path.join(__dirname, '..', 'dist');
const PUBLIC_DIR = path.join(__dirname, '..', 'public');

// Embed icon as base64 so it renders instantly with no network request or alt-text flash
const iconPath = path.join(PUBLIC_DIR, 'icon-192.png');
const iconBase64 = fs.readFileSync(iconPath).toString('base64');
const ICON_DATA_URL = `data:image/png;base64,${iconBase64}`;

const SPLASH_CSS = `
<style id="pwa-splash-css">
#pwa-splash{position:fixed;inset:0;z-index:99999;background:#060b16;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;transition:opacity 0.45s ease;}
#pwa-splash.hiding{opacity:0;pointer-events:none;}
#pwa-splash-glow{position:absolute;width:280px;height:280px;border-radius:50%;background:radial-gradient(circle,rgba(99,102,241,0.35) 0%,transparent 70%);animation:splashGlowPulse 2.4s ease-in-out infinite;}
#pwa-splash-icon{width:80px;height:80px;border-radius:22px;background-image:url('${ICON_DATA_URL}');background-size:cover;animation:splashIconIn 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards,splashIconPulse 2s ease-in-out 0.6s infinite;opacity:0;}
#pwa-splash-name{font-family:-apple-system,'Apple SD Gothic Neo','Noto Sans KR','Malgun Gothic',sans-serif;font-weight:900;font-size:38px;color:#f1f5f9;letter-spacing:-1px;opacity:0;animation:splashFadeIn 0.5s ease 0.5s forwards;}
#pwa-splash-divider{width:32px;height:1px;background:linear-gradient(90deg,transparent,#6366f1,transparent);opacity:0;animation:splashFadeIn 0.4s ease 0.8s forwards;}
#pwa-splash-slogan{font-family:-apple-system,'Apple SD Gothic Neo',sans-serif;font-size:13px;color:rgba(255,255,255,0.45);letter-spacing:0.3px;text-align:center;opacity:0;animation:splashSlideUp 0.5s ease 1s forwards;}
@keyframes splashIconIn{from{opacity:0;transform:scale(0.7)}to{opacity:1;transform:scale(1)}}
@keyframes splashIconPulse{0%,100%{transform:scale(1);box-shadow:0 0 0 0 rgba(99,102,241,0.5)}50%{transform:scale(1.06);box-shadow:0 0 0 12px rgba(99,102,241,0)}}
@keyframes splashFadeIn{from{opacity:0}to{opacity:1}}
@keyframes splashSlideUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
@keyframes splashGlowPulse{0%,100%{opacity:0.6;transform:scale(1)}50%{opacity:1;transform:scale(1.1)}}
</style>`;

const SPLASH_HTML = `
<div id="pwa-splash">
  <div id="pwa-splash-glow"></div>
  <div id="pwa-splash-icon"></div>
  <div id="pwa-splash-name">찰나</div>
  <div id="pwa-splash-divider"></div>
  <div id="pwa-splash-slogan">오늘의 트렌드를 한눈에 만나세요</div>
</div>
<script>window.hideSplash=function(){var r=document.getElementById('root');if(r)r.style.visibility='visible';var e=document.getElementById('pwa-splash');if(!e)return;e.classList.add('hiding');setTimeout(function(){e.remove();},500);};</script>`;

// Injected first in <head> so #root is hidden before any paint
const ROOT_HIDE_CSS = `<style id="pwa-root-hide">#root{visibility:hidden}</style>`;

function processHtml(content) {
  // 1. Hide #root before first paint (injected right after <head>)
  if (!content.includes('id="pwa-root-hide"')) {
    content = content.replace('<head>', '<head>' + ROOT_HIDE_CSS);
  }
  // 2. Splash CSS at end of <head>
  if (!content.includes('id="pwa-splash-css"')) {
    content = content.replace('</head>', SPLASH_CSS + '</head>');
  }
  // 3. Splash HTML before #root
  if (!content.includes('id="pwa-splash"')) {
    content = content.replace('<div id="root">', SPLASH_HTML + '\n<div id="root">');
  }
  return content;
}

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath);
    } else if (entry.name.endsWith('.html')) {
      const original = fs.readFileSync(fullPath, 'utf8');
      const updated = processHtml(original);
      if (updated !== original) {
        fs.writeFileSync(fullPath, updated, 'utf8');
        console.log(`✓ injected splash → ${path.relative(DIST_DIR, fullPath)}`);
      }
    }
  }
}

if (!fs.existsSync(DIST_DIR)) {
  console.error('dist/ not found. Run expo export first.');
  process.exit(1);
}

walk(DIST_DIR);
console.log('Splash injection complete.');
